# Simulating battles with random

# You need to import the random module to use the random functions. The random module is a built-in module in Python, so you don't need to install anything to use it.

import random


print("Your first enemy approaches. Prepare to battle!")
enemy = input("Choose a number, either 0 or 1: ") # The input function always returns a string, so we need to convert it to an integer before we can compare it to the random number.
beast = str(random.randint(0, 1)) # The random.randint(a, b) function returns a random integer N such that a <= N <= b. In this case, it will return either 0 or 1.

# This is our battle logic. You have a 50/50 chance of defeating the enemy. This occurs if the number you choose is the same as the random number generated by the computer. If you choose the wrong number, you are defeated and die.

if enemy == beast:
    print("You defeated the enemy!")
else:
    print("The enemy defeated you. \033[91mYou died.\033[0m")
    exit() # The exit() function is used to exit the program. We use it here to end the program if the player dies.
    
    
    
    print("Boss battle! It's time to face Margit, the Fell Omen!")
enemy = input("Choose a number from 0 to 9: ") 
beast = str(random.randint(0, 9)) # The random.randint(a, b) function returns a random integer N such that a <= N <= b. In this case, it will return any number between 0 and 9.

# This is our battle logic. You have a 1 in 10 chance of defeating the enemy. This occurs if the number you choose is the same as the random number generated by the computer. If you choose the wrong number, you are defeated and die.

if enemy == beast:
    print("You defeated the enemy!")
else:
    print("Margit has defeated you. \033[91mYou died.\033[0m")