# Validating Input
# You need to import the random module to use the random functions. The random module is a built-in module in Python, so you don't need to install anything to use it.

import random

# This is our battle logic. You have a 50/50 chance of defeating the enemy. This occurs if the number you choose is the same as the random number generated by the computer. If you choose the wrong number, you are defeated and die. However, if you enter something other than "0" or "1", you will also be defeated and die, because you did not enter a valid input. Let's fix that.

print("Your first enemy approaches. Prepare to battle!")
while True:
    enemy = input("Choose a number, either 0 or 1: ")
    if enemy == "0" or enemy == "1" or enemy =="uuddlrlrba": # You can see we use OR statements to see if our input is valid. This is fine when we have two or three options, but if we had more options, this would get very messy. We will learn a better way to do this in the boss battle.
        break # The break statement is used to exit the loop. We use it here to exit the loop once we have a valid input.
    else:
      print("You did not enter \"0\" or \"1\".") # This is the message that will be printed if the user enters an invalid input. It will then loop back and ask for input again until a valid input is entered.
            
        
beast = str(random.randint(0, 1))

if enemy == beast or enemy =="uuddlrlrba":
    print("You defeated the enemy!")
else:
    print("The enemy defeated you. \033[91mYou died.\033[0m")
    exit() # The exit() function is used to exit the program. We use it here to end the program if the player dies.
    

print("Boss battle! It's time to face Margit, the Fell Omen!")
    
while True:
    enemy = input("Choose a number from 0-9: ")
    if enemy in ["0", "1", "2", "3", "4", "5", "6", "7", "8", "9", "uuddlrlrba"]: # The in keyword is used to check if a value is in a list. This is much cleaner than using OR statements when we have many options.
        break
    else:
      print("You did not enter a number from \"0\" to \"9\".")
           
beast = str(random.randint(0, 9)) 

if enemy == beast or enemy =="uuddlrlrba":
    print("You defeated the enemy!")
else:
    print("Margit has defeated you. \033[91mYou died.\033[0m")